FROM node:18-alpine AS builder

WORKDIR /app

COPY package.json .
COPY yarn.lock .

RUN yarn

COPY . .

RUN yarn build

FROM node:18-alpine

WORKDIR /app

ENV NODE_ENV=production

COPY package.json .
COPY yarn.lock .
COPY ormconfig.js .

RUN yarn install --production

# 🔹 Crear la carpeta `uploads/` dentro del contenedor
RUN mkdir -p /app/uploads

# 🔹 Dar permisos a la carpeta `uploads/`
RUN chmod -R 777 /app/uploads

COPY --from=builder /app/dist /app/dist

EXPOSE 81

ENTRYPOINT [ "yarn", "start:prod" ]